kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: apache
  name: apache-role
rules:
- apiGroups: ["","apps","rbac.authorization.k8s.io"]
  resources: ["pods","deployments", "services", "hpa"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]